export const LOGIN = 'LOGIN';

export const FETCH_MY_MUSIC = 'FETCH_MY_MUSIC';
export const FETCH_COMMEND_MUSIC = 'FETCH_COMMEND_MUSIC';

export const SET_SELTED_STATUS = 'SET_SELTED_STATUS';

export const ADD_SINGLE_SELTED = 'ADD_SINGLE_SELTED';
export const ADD_MULTIPLE_SELTED = 'ADD_MULTIPLE_SELTED';

export const RENAME_MUSIC = 'RENAME_MUSIC';
export const DELETE_MUSIC = 'DELETE_MUSIC';
export const DELETE_REMAIN_MUSIC = 'DELETE_REMAIN_MUSIC';
