export default {
  SEARCH_STUDENT_LIST_BY_OPTION: 'SEARCH_STUDENT_LIST_BY_OPTION',

  FETCH_USER_INFO: 'FETCH_USER_INFO',
  FETCH_LESSON_INFO: 'FETCH_LESSON_INFO',
  FETCH_STUDENT_LIST: 'FETCH_STUDENT_LIST',
  FETCH_CLASS_INFO: 'FETCH_CLASS_INFO',
  FETCH_LESSON_SATISFIED_INFO: 'FETCH_LESSON_SATISFIED_INFO',
  REPLY_USER_FEED_BACK: 'REPLY_USER_FEED_BACK',

  FEACH_HOMEWORK_INFO: 'FEACH_HOMEWORK_INFO',

  FEACH_HOMEWORK_USER_UNREVIEW: 'FEACH_HOMEWORK_USER_UNREVIEW',
  FEACH_HOMEWORK_USER_REVIEW: 'FEACH_HOMEWORK_USER_REVIEW',
  FEACH_HOMEWORK_ALL_UNREVIEW: 'FEACH_HOMEWORK_ALL_UNREVIEW',
  FEACH_HOMEWORK_ALL_REVIEW: 'FEACH_HOMEWORK_ALL_REVIEW',

  REJECT_COMMENT: 'REJECT_COMMENT',

}