export default {
  SEARCH_STUDENT_LIST_BY_OPTION: 'SEARCH_STUDENT_LIST_BY_OPTION',

  FETCH_USER_INFO: 'FETCH_USER_INFO',
  FETCH_LESSON_INFO: 'FETCH_LESSON_INFO',
  FETCH_STUDENT_LIST: 'FETCH_STUDENT_LIST',
  FETCH_CLASS_INFO: 'FETCH_CLASS_INFO',
  FETCH_LESSON_SATISFIED_INFO: 'FETCH_LESSON_SATISFIED_INFO',
  REPLY_USER_FEED_BACK: 'REPLY_USER_FEED_BACK'
}